-- ⚠️ CLEAN RESET — run on a project with no real data. Drops existing tables.
drop table if exists public.stage_layouts cascade;
drop table if exists public.stage_results cascade;
drop table if exists public.tournament_players cascade;
drop table if exists public.tournament_settings cascade;
drop table if exists public.tournaments cascade;
drop table if exists public.players cascade;
drop table if exists public.judges cascade;

-- Players (global roster)
create table public.players (
  id uuid primary key default gen_random_uuid(),
  reg_no int generated by default as identity unique,
  name text not null,
  created_at timestamptz not null default now()
);

-- Judges (global)
create table public.judges (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

-- Tournaments (per-tournament settings)
create table public.tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  event_date date not null,
  enroll_start date,
  enroll_end date,
  capacity int,
  stage_names jsonb not null default '["Stage 1","Stage 2","Stage 3","Stage 4"]'::jsonb,
  stage_targets jsonb not null default '[0,0,0,0]'::jsonb,
  single_weapon_seconds_per_change numeric not null default 10,
  stage_weapon_changes jsonb not null default '[0,0,0,0]'::jsonb,
  created_at timestamptz not null default now()
);

-- Enrollment (global player ↔ tournament)
create table public.tournament_players (
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  status text not null default 'provisional' check (status in ('provisional', 'confirmed')),
  primary key (tournament_id, player_id)
);

-- Stage results
create table public.stage_results (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  judge_id uuid not null references public.judges(id) on delete restrict,
  stage int not null check (stage >= 1),
  factor text not null check (factor in ('major','minor')),
  alpha int not null default 0,
  charlie int not null default 0,
  delta int not null default 0,
  metal int not null default 0,
  pen_miss int not null default 0,
  pen_no_shoot int not null default 0,
  pen_safety int not null default 0,
  pen_out_of_zone int not null default 0,
  time_seconds numeric not null,
  single_weapon boolean not null default false,
  single_weapon_seconds numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, player_id, stage)
);

-- Stage layouts (placed elements per stage)
create table public.stage_layouts (
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  stage int not null check (stage >= 1),
  items jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (tournament_id, stage)
);

-- RLS: public read, authenticated write
alter table public.players enable row level security;
alter table public.judges enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_players enable row level security;
alter table public.stage_results enable row level security;
alter table public.stage_layouts enable row level security;

create policy "public read players" on public.players for select using (true);
create policy "auth write players" on public.players for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read judges" on public.judges for select using (true);
create policy "auth write judges" on public.judges for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read tournaments" on public.tournaments for select using (true);
create policy "auth write tournaments" on public.tournaments for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read enroll" on public.tournament_players for select using (true);
create policy "auth write enroll" on public.tournament_players for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read results" on public.stage_results for select using (true);
create policy "auth write results" on public.stage_results for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read stage_layouts" on public.stage_layouts for select using (true);
create policy "auth write stage_layouts" on public.stage_layouts for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
